### PR TITLE
bindShared() to singleton()

### PR DESCRIPTION
**Pull request by hiendv**
Please accept this PR !

### CODE REVIEW

**Comment by hiendv** [comment]
I'm thinking about creating a branch for laravel 5.2 since the Authentication is totally new.

**Comment by hiendv** [comment]
@andrewelkins It would be great if we can discuss about versioning Entrust. I think we should have a `laravel-5-2` branch because of authentication changes of Laravel 5.2

**Comment by Cannonb4ll** [comment]
How do you include this version in your composer.json exactly?

**Comment by hiendv** [comment]
@Cannonb4ll `repositories` to the rescue https://getcomposer.org/doc/05-repositories.md
Add my repository to `composer.json`
```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/hiendv/entrust"
        }
    ],
```
and specify the version of Entrust `"zizaco/entrust": "dev-laravel-5-2@dev",`

**Comment by Cannonb4ll** [comment]
@hiendv Wonderful mate! Thanks! :+1:

**Comment by hiendv** [comment]
@Cannonb4ll You're welcome !

**Comment by Thijmen** [comment]
:+1:

**Comment by hiendv** [comment]
To @Cannonb4ll, @bramburn  and others who are considering using my `laravel-5-2` branch:
I refactored Migration Command. The creatation of so-called Entrust Base and Entrust Pivot migration is now separated.

Entrust Base
* roles
* permissions
* permission_role

Entrust Pivot
* role_user
* ..etc (it depends on authentication drivers)

When executing `php artisan entrust:migration`, you can skip the Entrust Base migration and move to the later by entering **no**. So, if you want to migrate Entrust from the scratch with few drivers, you only need to process Base migration once.
screenshot from 2015-12-27 16-07-46

README.md will be updated soon

**Comment by Cannonb4ll** [comment]
Ah great, I was planning on using your branch today @hiendv , I will post feedback when I get stuck or something.

**Comment by Cannonb4ll** [comment]
Too bad this is taking long to get implemented :(

**Comment by hiendv** [comment]
We have to move on :sob:

**Comment by Cannonb4ll** [comment]
@hiendv You might know this aswell, do you know how to use the middleware from entrust in a controller method itself?

Let say I want to protect a function in my controller, I would go:

$this->middleware('permission', ['permission-here']);

But this does not seem to work, do you know a solution?

**Comment by andrewelkins** [comment]
Creating a branch for this right now.

**Comment by eliurkis** [comment]
@hiendv I'm using your laravel-5-2 branch. How can you define now a custom name for the "role_user_table" table?

**Comment by andrewelkins** [comment]
@hiendv Can you make a pull request to https://github.com/Zizaco/entrust/tree/5.2 and I'll merge it in there.

**Comment by dusterio** [comment]
@hiendv custom Blade directives are missing in your fork, so it's not fully compliant with Entrust documentation

**Comment by hiendv** [comment]
@eliurkis The pivot table between `user` and `role` is now automatically named based on you guards. I'll update the `MigrationCommand` and put some extra configurations in it.
If you're using an existing table, I'm afraid that it could not be fixed immediately. I'm working on it. However, if you create the migration from the beginning, you can rename the pivot table whatever you want.

@dusterio That's strange. I forked the master repo :persevere: I'm looking into it. It won't take long ;)

@andrewelkins Thank you. I'm resolving some conflicts but there are problems other than the migration. The authentication is totally changed, you know. I'm thinking about recreating a new branch for 5.2 and later versions from the scratch. Tons of workload though :sob:

**Comment by hiendv** [comment]
@andrewelkins I releazied that my branch `laravel-5-2` is a fork from `laravel-5` while your `5.2` branch is created from `master`. I don't get it? So `dev-master` or `dev-laravel-5` for Laravel 5?

**Comment by hiendv** [comment]
Ping @andrewelkins !

**Comment by Cannonb4ll** [comment]
Ping again @andrewelkins :+1:

**Comment by Cannonb4ll** [comment]
Have you heard anything from andrew @hiendv ?

**Comment by hiendv** [comment]
@Cannonb4ll Not a single signal :(

**Comment by The1NdNly** [comment]
Thanks @hiendv I'm using your fork! "This is major Tom to @andrewelkins"

**Comment by hiendv** [comment]
There is a problem guys. I forked the wrong branch due to the misunderstandings in the README, the consequence is various. I'm waiting for @andrewelkins 's confirmation of the right branch. So, I'm sorry to tell you that I don't recommend using my fork. I'm updating my README now..

**Comment by The1NdNly** [comment]
Thanks for the heads up @hiendv Looking forward to an official update, looking to add this to a new project I'm working on. ill guess ill wait since this is my 1st time using this. Thanks again dude.

**Comment by mickeyschwab** [comment]
@andrewelkins

**Comment by hiendv** [comment]
@The1NdNly Actually, Laravel Authorization Service is enough in most situations, IMO. You rarely need a *dynamic* role management system in an application. Sorry to say that :(

**Comment by The1NdNly** [comment]
Yup @hiendv , for now that’s what I’m using with my own middleware. however in this project I do need dynamic rolls, its what made me come looking here. but i don't need to implement it right now, ill come back when i do and see what’s changed :+1:

**Comment by atmikev** [comment]
@andrewelkins can we get some movement on this? Its really holding things up.

**Comment by MatthewRuddy** [comment]
Still waiting :(

**Comment by tdolph** [comment]
Why there is no fix for it after so long time? Makes me wonder if im doing the right thing by choosing this package... Hope it gets fixed soon :)

**Comment by lvandyk** [comment]
Merge please! :)

**Comment by bkuhl** [comment]
This is now a thing, this PR can be closed.

**Pull request closed without merging**
