### PR TITLE
Added alias to use IoContainer

### PR DESCRIPTION
**Pull request by moura137**

### CODE REVIEW

**Comment by andrewelkins** [comment]
I'm thinking this should actually be 'Entrust' instead of lowercase.

**Comment by GrahamCampbell** [comment]
No, lowercase is correct.

**Comment by GrahamCampbell** [comment]
Alias doesn't mean class_alias.

**Comment by GrahamCampbell** [comment]
It means $app->make('entrust') will be the same as $app->make(''Zizaco\Entrust\Entrust').

**Comment by andrewelkins** [comment]
Thanks!

**Comment by andrewelkins** [comment]
Closing this PR. Thanks @moura137

**Pull request closed without merging**
