### PR TITLE
Entrust permission caching

### PR DESCRIPTION
**Pull request by scottconnerly**
As discussed in issue #107

### CODE REVIEW

**Comment by scottconnerly** [comment]
Most platforms passed, PHP 5.4 failed because of some composer dependencies. What should be done about 5.4?

**Comment by andrewelkins** [comment]
We can drop 5.4. Can you change the travis requirements?

**Comment by scottconnerly** [comment]
Done, and the Composer php requirement too. All tests are passing.

**Comment by andrewelkins** [comment]
Awesome. Looks good.Thanks for the quick fix!

**Comment by screenager** [comment]
Hi Scott, unfortunately one of my applications runs in Laravel 4 and it does really a lot of permission checks per request. As I'm not really familiar yet with writing traits, how would you estimate the effort of rewriting this caching feature into the L4 branch ?

**Pull request merged**
