### PR TITLE
Update EntrustUserTrait.php

### PR DESCRIPTION
**Pull request by malutanpetronel**
Parent method returns true or false. We need to return that result too.

Signed-off-by: Petronel Malutan <malutanpetronel@yahoo.com>

### CODE REVIEW

**Comment by malutanpetronel** [comment]
[x] Created a fix for the trait used in the user model which is not returning called parent method response.

**Comment by malutanpetronel** [comment]
anybody seen this ?

**Comment by Tredde** [comment]
I support this pull request strongly. My code broke on the lack of the return values. Should be updated as soon as possible.

**Comment by pjmartorell** [comment]
@Tredde if you need these changes immediately the best you can do is fork this repo and require it in your composer.json

**Comment by approached** [comment]
@malutanpetronel your approach is well. But you forget to add in EntrustRoleTrait.php file?

**Comment by malutanpetronel** [comment]
The only problem I was noticing in the project I am working for, was when I saved a user. It could be that saving roles will fail too :)

**Pull request merged**
