### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gnanakeethan**
I think there was a typo.

### CODE REVIEW

**Comment by barhom** [comment]
Can somebody verify if this is correct ?

**Comment by FelipeUmpierre** [comment]
This update is correct. I was configuring my entrust and had the problem that Laravel wasn't found \Entrust::can function

**Comment by gnanakeethan** [comment]
@Zizaco can you please make the merge? 

Thanks,
Gnanakeethan

**Comment by insign** [comment]
Truly

**Pull request merged**
