### PR TITLE
Bypass cache when file or database cache drivers are set

### PR DESCRIPTION
**Pull request by pjmartorell**
Bypass cache when `file` or `database` cache drivers are set.
Solves #541, #537, #450, #422.

### CODE REVIEW

**Comment by Tredde** [comment]
Also check pull request #545 for fixing the EntrustUserTrait.php file lacking return values for the save, delete and restore functions.

**Comment by pjmartorell** [comment]
@Tredde Sorry, but I don't see the relation between my pull request and the pull request #545 you mentioned. What do you mean? thanks

**Comment by jnbn** [comment]
up

**Comment by tyler-shaw** [comment]
This fixes the `This cache store does not support tagging` issue, correct? Can we please get a version release? I'm (_im_)patiently waiting for this fix so that I can upgrade my Entrust version. I'm stuck on v1.4.1 which doesn't have middleware until this fix is out.

**Comment by pjmartorell** [comment]
@tyler-shaw You don't need to wait until an official release since you can set Composer to pull the package directly from the master branch.

**Comment by tyler-shaw** [comment]
@pjmartorell I was under the impression that pulling master could lead to a `composer update` accidently pulling in potentially breaking changes applied to master. I prefer to specify a specific release, but I'll go with master temporarily and specify a release whenever it's available. Thanks

**Comment by ryzr** [comment]
Please tag this release! :)

**Comment by cent040** [comment]
First i was getting problem when i use 
"zizaco/entrust": "5.2.x-dev"

Solved my problem in Laravel5.3 after 
"zizaco/entrust": "dev-master#6a0fd8c3b73037b4855c6c4eaf1060788c0df1e9"

**Comment by cent040** [comment]
First i was getting problem when i use 
"zizaco/entrust": "5.2.x-dev"

Solved my problem in Laravel5.3 after 
"zizaco/entrust": "dev-master#6a0fd8c3b73037b4855c6c4eaf1060788c0df1e9"

**Pull request merged**
