### PR TITLE
Placeholder Support to Permission Check

### PR DESCRIPTION
**Pull request by hkan**
This is be useful for the people that namespace their permissions like me. With this PR, it will be possible to check permissions like `$user->can('posts.*')` to see if user has any permission under the `posts` namespace.

### CODE REVIEW

**Comment by andrewelkins** [comment]
This is really cool. Can you update the readme? Then I'll merge it.

**Comment by Zizaco** [comment]
Pretty cool. The only think I'm missing is some tests to make sure everything is working properly (and to warn if anything break later)

**Comment by unitedworx** [comment]
Any updates on pulling this in? Seems really really useful if you namespace your permissions!

**Comment by phroggyy** [comment]
@unitedworx: it's still missing tests, isn't it?

**Comment by hkan** [comment]
It is missing. I'll work on that tonight.

**Comment by andrewelkins** [comment]
merged @unitedworx PR. Closing this one.

**Pull request closed without merging**
