### PR TITLE
Added permission check against role

### PR DESCRIPTION
**Pull request by Yelldon**
Added a check to see true or false against a role to see the permissions it has assigned to it.  Useful for changing permissions on roles in a UI.  That is if others find it useful as well.

### CODE REVIEW

**Comment by imnotjames** [comment]
Because the attach method is named `attachPermission` would it make more sense for this function to be named `hasPermission`?

**Comment by Yelldon** [comment]
There is a method on the trait that is also called `perm`, so at the time, I was trying to be consistent with that.  But you're probably right, `hasPermission` may be more consistent with the other methods.

**Comment by andrewelkins** [comment]
Can you change this to hasPermission?

**Comment by malhal** [comment]
This is exactly what I needed! Thanks

**Comment by malhal** [comment]
You could also update line 109 "// Validate against the Permission table" of the UserTrait to make use of this new function too.

**Comment by Athi-BON** [comment]
doesn't the method have to be included in the Interface?

**Pull request merged**
