### PR TITLE
Move test file to autoload-dev to fix composer update

### PR DESCRIPTION
**Pull request by tuwannu**
Fix for #391, #394, #396

### CODE REVIEW

**Comment by tuwannu** [comment]
Meanwhile waiting for PR to be accepted. Here's a workaround by adding "repositories" and changing zizaco/entrust to use `dev-middlewaretest-fix`.

    {
        ...
        "repositories": [
            {
                "url": "https://github.com/tuwannu/entrust.git",
                "type": "git"
            }
        ],
        "require": {
            ...
            "zizaco/entrust": "dev-middlewaretest-fix",
            ...
        },
        ...
    }

**Comment by Profeten** [comment]
Hi, I am not sure I've understood everything here! But I've added the repositories array as well as the require middlewaretest-fix and done composer update, composer dump-autoloader but the problem persists! :/

**Comment by tuwannu** [comment]
This pull request has already been merged. There is no need to put a workaround on this. Simply require

    "zizaco/entrust":"dev-master"

in your composer.json, without any additional changes I mentioned in this pull request, should work fine.

**Comment by Profeten** [comment]
Ok let's see I am still getting the same error "ReflectionException in Container.php line 737:
Class App\Http\Zizaco\Entrust\Middleware\EntrustRole does not exist"

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "intervention/image": "^2.3",
        "zizaco/entrust": "dev-master"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}


# composer update

> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing predis/predis (v1.0.3)
  - Updating zizaco/entrust (dev-middlewaretest-fix 8d88ff4 => dev-master 3b41a8e)
    The package has modified files:
    M src/Entrust/Middleware/EntrustRole.php
    Discard changes [y,n,v,d,s,?]? y
    Checking out 3b41a8ec0cdba8400eab344f919291bcc59c0115

Writing lock file
Generating autoload files
> php artisan optimize
#

**Comment by tuwannu** [comment]
Your composer.json file looks alright.

From the error message, it should not be trying to find `App\Http\Zizaco\Entrust\Middleware\EntrustRole`, but rather `Zizaco\Entrust\Middleware\EntrustRole`. Are you sure you are doing your code right?

**Comment by Profeten** [comment]
Aliases
        'Entrust'   => Zizaco\Entrust\EntrustFacade::class,

providers
        Zizaco\Entrust\EntrustServiceProvider::class, 

    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'role' => Zizaco\Entrust\Middleware\EntrustRole::class,
        'permission' => Zizaco\Entrust\Middleware\EntrustPermission::class,
        'ability' => Zizaco\Entrust\Middleware\EntrustAbility::class,
    ];

**Comment by Profeten** [comment]
I actually solved the problem and for future reference there needs to be a \ before the Zizaco i.e

protected $routeMiddleware = [
    'auth' => \App\Http\Middleware\Authenticate::class,
    'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
    'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
    'role' => \Zizaco\Entrust\Middleware\EntrustRole::class,
    'permission' => \Zizaco\Entrust\Middleware\EntrustPermission::class,
    'ability' => \Zizaco\Entrust\Middleware\EntrustAbility::class,
];

Rather than

protected $routeMiddleware = [
    'auth' => \App\Http\Middleware\Authenticate::class,
    'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
    'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
    'role' => Zizaco\Entrust\Middleware\EntrustRole::class,
    'permission' => Zizaco\Entrust\Middleware\EntrustPermission::class,
    'ability' => Zizaco\Entrust\Middleware\EntrustAbility::class,
];

That's just basic namespacing but if anyone else find themselves in this position it's probably because you just copy pasted the code from the git page like myself :)

**Comment by robertmindroi** [comment]
@Profeten +1

**Comment by nhtua** [comment]
@Profeten +1

**Pull request merged**
