### PR TITLE
Fixed broken migration command 

### PR DESCRIPTION
**Pull request by vijaythecoder**

### CODE REVIEW

**Comment by andrewmclagan** [comment]
(Y)

**Comment by FelipeUmpierre** [comment]
:+1:

**Comment by yarrgh** [comment]
:+1:

**Comment by NeilyoSummer** [comment]
nice

**Comment by freel132** [comment]
thx

**Comment by JillzTom** [comment]
Thanks. It worked.

**Comment by cjameszignal** [comment]
+1

**Comment by justinr1234** [comment]
+1 ... any eta on this being merged?

**Comment by juliancesar** [comment]
+1

**Pull request merged**
