### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by akshayagarwal**
Update to reflect Laravel 5.1 conventions

### CODE REVIEW

**Comment by jyhsu2000** [comment]
I think some single quotes are unnecessary.
The following codes are more close to usage of Laravel 5.1
```php
Zizaco\Entrust\EntrustServiceProvider::class
```
and
```php
'Entrust' => Zizaco\Entrust\EntrustFacade::class
```

**Comment by GrahamCampbell** [comment]
> I think some single quotes are unnecessary.

Worse than that. Including the quotes breaks the code completely...

**Comment by GrahamCampbell** [comment]
I'm :-1: here anyway. It's not a convention.

**Comment by akshayagarwal** [comment]
Fixed the unnecessary quotes. @GrahamCampbell We have had this discussion earlier on another repo so won't go into it again. I just think it would be easier to merge this change (thinking that core too follows this style) than deliberate on whether its a useful PR. If you still disagree, please close the PR.

**Pull request closed without merging**
