### PR TITLE
Added laravel 5.1 support

### PR DESCRIPTION
**Pull request by mpociot**
Added laravel 5.1 support

### CODE REVIEW

**Comment by BlueManLine** [comment]
+1

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by gmsantosxl** [comment]
-1

The tilde constraint already does that: https://getcomposer.org/doc/01-basic-usage.md#package-versions

**Comment by GrahamCampbell** [comment]
This PR is WRONG. `~5.0` ALLOWS 5.1 use.

**Comment by BlueManLine** [comment]
Hmmm... indeed!

I have hade some eclipse, than I required the package to project and everything is working fine.

**Comment by andrewelkins** [comment]
This PR isn't needed, as others have states, the ~ takes care of 5.1. Thanks for taking the time to contribute.

**Pull request closed without merging**
